### ISSUE TITLE
Bar soft wraps if terminal window is too narrow (wide unicode chars are tricky)

### ISSUE THREAD

**Issue by igoro00** [rsalmei/alive-progress#19] opened 2019-12-08 13:16 UTC
As in the title: when terminal window is too narrow progress bar stops animating and it prints itself line by line.

I'm using code from README:

```
with alive_bar(len(text)) as bar:
    for i in range(len(text)):
        #do some stuff
        bar(text="xd", incr=1)
```

Here's output:
![2019-12-08-14-08-43](https://user-images.githubusercontent.com/35789870/70389798-a32ad880-19c4-11ea-8a6e-cb8f87730989.gif)

**Comment by rsalmei** [comment] 2020-01-26 04:14
Hey @igoro00, thank you.

Unfortunately it is well known, but I'm not sure how to fix that. I'm going to study how could I extract the current terminal width, and if the bar would use more than it, do one of two things:

1. truncate the output
2. shorten the bar length

But I can not guarantee it can be done, only that I'll try... 👍

**Comment by igoro00** [comment] 2020-01-26 14:47
ok, so i found something simple that would work, but only for versions >= 3.3 (python2 is EOL either way, i.e. next version of Fedora won't ship with python2 at all)

i haven't tested it yet because I don't have access to my pc rn. Maybe tomorrow.

```
from sys import version_info
if version_info>=(3,3):
    from os import get_terminal_size
    ts = get_terminal_size()
    print(ts.lines) #prints int of lines
    print(ts.columns) #prints int of columns
```

**Comment by igoro00** [comment] 2020-01-26 15:08
it works on pydroid3 with python 3.7.2

Also get_terminal_size() gets current terminal size so if you put it inside a loop and resize the window it'll update properly.

**Comment by RHQ-Rusty** [comment] 2020-04-13 01:20
@igoro00 how would you encapsulate the loop for the alive_bar inside of another loop to dynamically update the column count as needed? I'm working with something that takes two inputs and scans between them. 0-100 will work fine, but 0-2500 will cause the "running down the screen bar" issue that you're having. I'm looking to use the terminal columns counter to dynamically scale the bar depending on how big the values passed are to avoid this issue.

You can see a snippet of my code in Issue #30!

**Comment by rsalmei** [comment] 2020-04-13 04:17
As I've said in the other issue, you can counter this behaviour with a simple argument `length=N`, N being less than 40, which is the default size. Something like `length=30` or even `length=20` should give you plenty of space to put some text in the bar.
I think this should greatly mitigate this problem, while there isn't support to screen width auto detect.

**Comment by rsalmei** [comment] 2020-05-14 03:04
Hello,

I've been trying to implement this in the new, unreleased 2.0 version, but it is way trickier than anticipated.

I wrote just now a small code that should show what to expect, could you try it and report back?

```python
from itertools import cycle
from shutil import get_terminal_size

asd = cycle('12345')
while 1:
    x = get_terminal_size().columns
    print('\033[2K\r' + (next(asd) * x) + '\r', end='')
    time.sleep(1/60.)
```

In my experience, there's absolutely no way to keep the terminal from garbaging the screen. Experiment the effects, both slowly decreasing the terminal and slowly increasing it...
What do you think?

**Comment by MartinHammarstedt** [comment] 2020-05-15 08:03
That indeed produces garbage when narrowing the terminal window. Maybe the resizing problem is impossible to solve, but currently alive-progress produces garbage even with a fixed terminal size, if it happens to be too narrow. Truncating the output to the terminal width would at least solve that problem.

**Comment by rsalmei** [comment] 2020-05-17 01:03
Humm, you're right. It really would be better to try to start with a solution that gets the terminal size only at init time, not inside the running thread, and get to resolve just that.
Gonna work on that 👍

Unfortunately it should come only in the v2, which supports python 3 only.

**Comment by MartinHammarstedt** [comment] 2020-05-17 10:22
Great! However I think checking the size continuously might still have its uses. Resizing the terminal would still produce garbage, but that garbage would only be produced while resizing. Without continuous checking the garbage would continue to be produced forever.

Possibly the most important advantage of continuous checking would be when you've started a process and realize that the terminal window is too narrow to read all the messages, so you make the window bigger. If we're only checking the size once, the messages would then continue to be truncated, not using the new space available.

**Comment by rsalmei** [comment] 2020-05-20 16:03
You're right again, excellent insights! Indeed it would be helpful to continuously check the terminal, even with garbage being unavoidable...

Actually this is somewhat tricky to implement, as the bar and spinner precalculate several positions and strings to be able to animate that fast, and any change in screen requires recreating them. So they need to be created inside an inner function, not as local variables, and correctly lock the animation thread while doing that, since it is using those variables...

Fortunately, I'm at this moment implementing another feature that will also require recreating them! In v2 I'm creating the concept of entering the bar context in a "precalculate mode", so one can calculate the needed total to send to the very same bar, and get an elapsed time and spinner while doing that. Then it will be possible to restart the running bar with the actual total, resetting the timer and getting an accurate throughput. Anyway, I can use the same reconfiguration ability for this.

**Comment by rsalmei** [comment] 2020-05-20 16:16
Oh, forgot to say, very important to grasp my comment: I'm not only truncating the output, I'm actually adapting the bar to the available space. So, the bar will be the most elastic one, which gets the remaining space. There's now an actual `title`, that appears on the left, fixed, and situational messages on the right, fixed. If the space is too narrow even with the smallest bar, then I'll truncate.
I'm also considering putting some scrolling spinners to good use! If the title or the messages happen to be too big, I could put a scrolling signboard to roll them...

**Comment by rsalmei** [comment] 2020-07-07 03:36
Hello @MartinHammarstedt, how are you?

Good news, this is ready and working! 🎉
After realizing that v2 was getting way too big, I've decided to split this implementation in two: now we'll get a static soft wrap behavior right in this major (so including python 2 support), and someday that adaptive one I've talked about.

This new version will include:
1. soft wrapping support
2. hiding cursor support
3. logging support
4. exponential smoothing of ETA data
5. proper bar title

Wow, that will make a very mature and feature complete progress bar for python 2, ready to expand for python 3 only.

**Comment by rsalmei** [comment] 2020-07-07 03:48
Here it is:
![wrap_support](https://user-images.githubusercontent.com/6652853/86704663-7fc41c80-bfeb-11ea-859b-145135fd3765.gif)

**Comment by MartinHammarstedt** [comment] 2020-07-07 08:14
That's great news, thanks for letting me know! I'm looking forward to the release!

**Comment by rsalmei** [comment] 2020-07-07 22:16
The technical part of the PR is ready, gonna update its documentation now!
==> https://github.com/rsalmei/alive-progress/pull/46

**Comment by rsalmei** [comment] 2020-07-10 00:30
It's released!! 🥳 
Care to test it and share, please?

**Comment by MartinHammarstedt** [comment] 2020-07-10 10:10
Nice work! It seems to work well, aside from one thing. The width of the output is calculated using `len()`, which only counts characters and not the space they actually take up on the screen. Wide Unicode characters like "ＷＩＤＥ" or emojis like "😺" often take up two columns, and as a result the problem with wrapping persists if you use such characters in the title or status message.

I have no experience with this, but maybe you could use `unicodedata.east_asian_width()` or the [wcwidth](https://github.com/jquast/wcwidth) library to help calculating actual screen width used.

`unicodedata.east_asian_width("😺")` -> `'W'` (as in "wide")
`wcwidth.wcswidth("😺")` -> `2`

In my case it's a single emoji that causes the trouble, but I found I can work around the problem by adding a zero width space character as well, as it won't take up any space on the screen but will be counted by `len()`, making the length match the space used. Not a very nice solution, but it works!

**Comment by rsalmei** [comment] 2020-07-10 16:44
Thanks man!
Wow, unicode is hard... I didn't know about those wide characters!
But thank you about both the analysis and your possible solution, a zero width space could work for the general case too, if I manage to insert those automatically, matching the number of wide chars...
I'm going to try that, and get back to you! 👍

**Comment by rsalmei** [comment] 2020-07-11 00:43
Hey @MartinHammarstedt, it's a little trickier than anticipated.

I've counted those characters known as Wide in both title and text. Then discounted its sum from the `len()`, which should be enough to not use any ZWSP. But when the line is truncated to the needed length, part of these characters may be stripped off the string...... Argh, so that sum is no longer valid...

Well, I can iterate the strings and find out how much characters I can include in the needed length, but I would need to do that in all refreshes, which I definitely don't want to.
So, I think ZWSP is not a bad solution, at all! If I include them right before all of those characters, I could do this operation just once! It has to be right before each one of them because that would also make work the word boundaries, where one more character needed could imply in 2 more being added, that way it's the ZWSP that will be out, which may not align things properly, but at least will not extrapolate the screen.

Which char did you use?
- zero-width space (ZWSP): U+200B
- zero-width non-joiner (ZWNJ): U+200C
- zero-width joiner (ZWJ): U+200D

I'm asking because I'm my macOS iTerm2 terminal, the ZWSP seems to be the only one that **does not** work... 🤔 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/6652853/87212727-6cb89180-c2f6-11ea-8a2f-7de431dc0204.png">

**Comment by rsalmei** [comment] 2020-07-11 19:59
Hey, you didn't answered yet, but I have good news, I've made it work! 🎉 
But there's a few quirks, look at that!

The common case, the one you actually reported, worked from 3.6 onward:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/6652853/87232651-06d01680-c397-11ea-98cc-2e9e5d6b0ab3.png">
The width is indeed `'W'`, and my new `sanitize_text_marking_wide_chars` does:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/6652853/87232667-29fac600-c397-11ea-96fa-f31c57711a36.png">

Curiously, in 2.7 unicodedata returns it wrong:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/6652853/87232693-5dd5eb80-c397-11ea-8e63-21dcfa0ae398.png">
So my sanitize doesn't, but magically it works!
<img width="722" alt="image" src="https://user-images.githubusercontent.com/6652853/87232710-7f36d780-c397-11ea-90a8-c48db7af61f8.png">
Yeah, the unicode version 8.0 in python 2.7 appear to encode that with 2 bytes already.

But in 3.5 specifically:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/6652853/87232731-a5f50e00-c397-11ea-99da-48b1769edf7a.png">
My sanitize doesn't work either, and the unicode version 9.0 encode it differently:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/6652853/87232748-d3da5280-c397-11ea-8494-407160e7f0ec.png">

Tricky humm?

**Comment by rsalmei** [comment] 2020-07-11 22:53
Hey I just released it!!
Can you test it again?

**Comment by MartinHammarstedt** [comment] 2020-07-13 09:27
I just tried it and it seems to working great (in Python 3.7.5 at least)! However, in `sanitize_text_marking_wide_chars` you should check not only for "W", but also "F" and "A". "F" is "Fullwidth" (like these characters: "ＷＩＤＥ") and "A" is "Ambiguous". I don't know what the difference is between Wide and Fullwidth, but both take up two columns in my terminal, and Ambiguous are characters that _may_ be wide, so it's safest to count them as wide.

As for which character I used in my workaround, I used the zero-width space. All three characters you listed work identically in my Ubuntu terminal, so the zero-width joiner you're using works just as well.

**Comment by rsalmei** [comment] 2020-07-13 17:10
I'm glad it worked!
It was harder than I initially thought... 😅 

But I'm not sure about the 'F' and 'A'... I know the latter seems to **not** be treated as wide.
According to Unicode [East Asian Width][1] - Section 5 Recommendations:
>When processing or displaying data
>
>   - **Wide** characters behave like ideographs in important ways, such as layout. Except for certain punctuation characters, they are not rotated when appearing in vertical text runs. In fixed-pitch fonts, they take up one Em of space.
>   - **Halfwidth** characters behave like ideographs in some ways, however, they are rotated like narrow characters when appearing in vertical text runs. In fixed-pitch fonts, they take up 1/2 Em of space.
>   - **Narrow** characters behave like Western characters, for example, in line breaking. They are rotated sideways, when appearing in vertical text. In fixed-pitch East Asian fonts, they take up 1/2 Em of space, but in rendering, a non-East Asian, proportional font is often substituted.
>   - **Ambiguous** characters behave like wide or narrow characters depending on the context (language tag, script identification, associated font, source of data, or explicit markup; all can provide the context). **If the context cannot be established reliably, they should be treated as narrow characters by default.**
>   - Emoji style standardized variation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value.
>

Note the 'F' Fullwidth is not even cited in this text.
And in fact, according to the images I've posted about Python 2.7 above, if I include Fullwidth I'll break it in Python 2.7, making a string of length 3 instead of 2 (it already had that length in the old unicode ucd 8.0). So I can't do that.

That is beyond tricky... 😓 

[1]: https://www.unicode.org/reports/tr11/tr11-31.html

**Comment by rsalmei** [comment] 2020-07-15 17:47
Well, I've decided to include 'F' indeed, but only in the next major, which will drop python 2.7 support.
That way I can maintain its compatibility, without losing much in the other versions.
Thank you for all your insights again!

**Comment by MartinHammarstedt** [comment] 2020-07-16 10:15
Sounds like a good decision! 👍

**Comment by rsalmei** [comment] 2020-07-16 18:04
Nice, I hope it's working nicely now, with no little hacks whatsoever!

**Comment by rsalmei** [comment] 2020-08-25 06:31
Hey @MartinHammarstedt, how are you?

Fun fact, guess what I'm struggling now to release #51 ? Yes, wide unicode chars........ 😂 
I realized I included support for the title and situational message, which is nice, but forgot about the spinners!
If you create a customized one and use the widies, it will all break again.... 😓 

And now it is a little more complex, if you can believe that...
See: titles are fixed, and messages are truncate only, but spinners have animations, which can make these characters go in and out of display area!
- frame spinners can have frames with or without them, so I need to equalize their lengths;
- scrolling spinners need to make them **smoothly** enter and exit the screen, so I need to place actual spaces in place if the ZWJ would be displayed or if it has just left the screen, both at either sides.....

The scrolling are hard to implement efficiently, the frames are done!
![asd](https://user-images.githubusercontent.com/6652853/91131468-4a4ebd80-e683-11ea-9bdc-cd02b2677abe.gif)

Regards! 👍

**Comment by rsalmei** [comment] 2020-09-19 17:24
Yeah, after I've made the frame spinners work, it took 25 more days to make all the others work too! 😅 
Well, I'm going to keep this open for now, to see what will enter in the next milestone.

**Comment by rsalmei** [comment] 2020-09-20 21:03
Hey, another chapter in the wide chars saga... 😞 
I just found Variation Selectors! https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)

It seems some characters already have length=2 in python, the ones that have a VS immediately following them...
For those, I think I should maintain the VS, while not fixing the way I did until now. But this would require a different technique to detect and fix truncated strings with wide chars inside.

To use both methods at the same time would be cumbersome and tricky, but how to unify them? If there isn't any VS, could I insert a "default" one? Wow...

**Comment by MartinHammarstedt** [comment] 2020-09-21 17:18
Great work on all this 👍, and I'm sorry that Unicode keeps finding new ways to make life hard for you! I'm afraid I don't have any great advice to give. I was going to suggest that you have a look at the [wcwidth](https://github.com/jquast/wcwidth) library (whose sole purpose is calculating widths of Unicode strings in the terminal) to see how they tackled the problem, but then I noticed that they don't seem to support Variation Selectors either. So at least you're not alone! 😅

**Comment by rsalmei** [comment] 2020-09-21 17:45
Yeah, thank you @MartinHammarstedt.

I already implemented these two variant forms:

```
# unicode variant forms, this is very tricky, and in no way comprehensive.
VARIATION_SELECTORS = tuple(chr(0xfe00 + i) for i in range(16))  # unicode variation selectors.
EMOJI_MODIFIER_FITZPATRICK = tuple(chr(0x1f3fb + i) for i in range(5))  # unicode skin colors.
```

And I came up with a third method, instead of using 1. Zero Width chars before widies and 2. default variant forms after them when missing...
I've changed the ZWJs insertion to after the widies, only insert them if there's no known variation following it, reversed my fix truncation algorithm to detect it after the chars, included all the variations above in that detection, and finally created a new `iter_wide` algorithm that delivers "complete chars", including their variations... 😅
So all **currently known** wide chars are marked, with its original variant form or a ZWJ! It seems to be working nicely!

I may end up with better support for Unicode then wcwidth do! 😝

**Comment by rsalmei** [comment] 2020-09-22 04:16
😂 My `iter_wide` is broken... Just found out the Fitz Patrick skin modifiers **can also be used as chars, WIDE chars**......
So I must, at the same time, look at both the preceding and following chars... argh

**Comment by rsalmei** [comment] 2020-09-25 18:36
Ok, it is working, now I do support wide chars and Fitz Patrick skin tones variation, it was hard to support it, came up with the following combinations table:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/6652853/94301232-991c9b00-ff40-11ea-814c-a932f868e882.png">

The bad news is: excited, I tried to include a few spinners with a variety of cool emojis, like these ones:
```python
    flora = bouncing_spinner_factory('☘️🌱🌲🌳🌴🌵🌾🌿🍀🍁🍂', 8, 2)
    balls = scrolling_spinner_factory('🏀🏈🏉🏐🏓⚾️🥎⚽️🧶🎾🎱', 3, 1)
    fruits = bouncing_spinner_factory('🍎🍍🍌🍋🍊🍉🍈🍇🍅🍓🍒🍑🍐🍏', 10, 3)
    flowers = bouncing_spinner_factory('💐🌷🌸🌹🌺🌻🌼', block=3)
    elements = bouncing_spinner_factory('🔥🌊💨️⚡️', block=1)
```

When the spinner engine broke wildly with: `ValueError: invalid string with unicode modifiers`.
Humm... Then I've discovered... I was only scratching the surface of Unicode!!! 😞 
The very first character "☘️" is formed by: 
```python
In [24]: [(x, hex(ord(x)), unicodedata.east_asian_width(x)) for x in '☘️']
Out[24]: [('☘', '0x2618', 'N'), ('️', '0xfe0f', 'A')]
```
It's two characters, so wide is any sense, but has east asian width **Neutral**... So I cannot trust this info.

Then I finally discovered in [this article](https://blog.emojipedia.org/emoji-zwj-sequences-three-letters-many-possibilities/) that the size a character occupies on screen has NOTHING to do with their encoding!!
There's even "two women kissing" that's formed by an astounding combination!!
```python
In [17]: [(x, hex(ord(x)), unicodedata.east_asian_width(x)) for x in '👩‍❤️‍💋‍👩']
Out[17]:
[('👩', '0x1f469', 'W'),
 ('\u200d', '0x200d', 'N'),
 ('❤', '0x2764', 'N'),
 ('️', '0xfe0f', 'A'),
 ('\u200d', '0x200d', 'N'),
 ('💋', '0x1f48b', 'W'),
 ('\u200d', '0x200d', 'N'),
 ('👩', '0x1f469', 'W')]
```
That's 8 chars on string, to occupy probably two on screen.
This [article](https://hsivonen.fi/string-length/) is also very informative, although so long I couldn't read it all.

I'm very disappointed. It's probably the forth time I've refactored all the spinner engine to support these chars. This has brought very very cool additions, like the spinner compiler, but it seems to be infinite.
The architecture I came up till now is based on "chars with dual cell on screen have length two in Python", but this discovery breaks it badly. I do like challenges, but come on Unicode! 😖

**Comment by rsalmei** [comment] 2020-10-05 20:07
Hey @MartinHammarstedt,

Another hit on a wall. I just found that I can't insert ZWJ to adjust the size of the text... Well I already couldn't when I found out about the grapheme clusters, that could take way several chars in sequence, but I'm talking now about the initial ones, those alone, that have unicode east asian width of Wide or Fullwidth! These chars can be used alone or in group, meaning different things...

Example:
[1f9d1](http://www.unicode.org/emoji/charts/full-emoji-list.html#1f9d1) -> person [🧑]
[1f393](http://www.unicode.org/emoji/charts/full-emoji-list.html#1f393) -> graduation cap  [🎓]
[1f9d1 200d 1f393](http://www.unicode.org/emoji/charts/full-emoji-list.html#1f9d1_200d_1f393) -> student [🧑‍🎓]

Yeah... A ZWJ arbitrarily put inside the string can alter its meaning....... It doesn't work.

**Comment by rsalmei** [comment] 2020-10-08 00:41
Hey, finally some great news!
After some major refactors, again, I've created the infrastructure to support grapheme clusters!! **Actually** support them... 😅 
Now the spinners will not deal internally with strings anymore, but with tuples of "columns", that's the big change! And the original sequence are never modified in any way, not even on screen!!
When one char is presumed to use two columns, it is marked with a `None` in sequence, which is removed when rendered on screen, but do impact `len()` and makes it easier to detect truncated chars!
Well it's only the infrastructure for now, but it's more than promising, the simplest one `frame_spinner_factory` has just worked!

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/6652853/95402081-3a163900-08e5-11eb-9a14-154f70e1e1da.png">

**Comment by rsalmei** [comment] 2020-10-09 00:32
Scrolling is working too! 🎉 
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/6652853/95528177-c4c26b00-09ad-11eb-984a-ee6a45e1e182.png">

**Comment by rsalmei** [comment] 2020-10-09 03:37
Ok, I'm on a roll!
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6652853/95540619-99e51080-09c7-11eb-8e26-59f7cbfed913.png">

**Comment by rsalmei** [comment] 2020-10-09 03:47
Testing with block mode is another thing entirely, where all graphemes should scroll isolated. Here I have to remove the column marks of wide chars, iterate on all of them reapplying the marks, multiply by the block size, truncate the resulting string, and finally fixing any truncated wide char at the end... 
Yeah, working! 🎉 
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6652853/95541112-e250fe00-09c8-11eb-8195-7570079cc34d.png">
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6652853/95541130-ee3cc000-09c8-11eb-9e3b-f0bb5b10d2ec.png">
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6652853/95541146-f39a0a80-09c8-11eb-8f6b-0ba2646753a3.png">

**Comment by MartinHammarstedt** [comment] 2020-10-09 17:44
Hey, great work! 😄 It's good to see that you haven't given up, despite all the surprises Unicode keeps throwing at you!

**Comment by rsalmei** [comment] 2020-10-10 01:47
Thank you man!
But actually I've decided to stop trying to detect the unicode graphemes on my own, which is kind of giving up, but I realized I would be much better served by a dependency for managing that. 😅
I've seen that I was investing so much time in something that 1. was not the core of my project, 2. changes every year, 3. could be nicely provided by the excellent python dependency mechanism, and most importantly 4. was keeping me from refactoring all the other components that needed to learn how to deal with streams of graphemes once that did work... And that *is* the core of my project!!

**Comment by rsalmei** [comment] 2020-10-10 03:02
ALL the spinners are WORKING!!! Now `alongside_spinner_factory` and `delayed_spinner_factory` 🎉🥳
I think this is one the most advanced pieces of code I've ever written. Grown out of one of the greatest challenges I had the pleasure to tackle! (look for the `spinner_compiler` once I commit it...)

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/6652853/95644121-a1b9b900-0a8a-11eb-9bb6-71d9df9e3257.png">
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/6652853/95644142-e80f1800-0a8a-11eb-9322-2bb39d126314.png">

**Comment by rsalmei** [comment] 2020-10-10 17:43
For history sake, this is what it was when I started this endeavor:
![image](https://user-images.githubusercontent.com/6652853/95661561-ab810200-0b06-11eb-8e64-5dc0b104b0a0.png)

It has gone a long way...
Now I'll start to include this support in the bars subsystem, and then make the progress bar work again, using the new stream of graphemes architecture... 👍

**Comment by rsalmei** [comment] 2020-10-22 20:03
Hey @MartinHammarstedt, how are you man?

Well, I've been studying the basic problem today, and I think I found a way to not produce garbage on screen!
I've used *Save Current Cursor Position* and its Restore, to a very nice effect!
On normal movement the screen keeps almost pristine! Save for a few blank lines that appear on top. On fast movements sometimes a garbage does appear, but it is very minimal.

How cool is that?
![asd](https://user-images.githubusercontent.com/6652853/96923913-52ab5500-1488-11eb-8c80-15e83ea229a7.gif)

This is the code if you want to try:

```python
from itertools import cycle
from shutil import get_terminal_size
import time

asd = cycle('12345')
print('\033[s')  # <-- saves the cursor position
while 1:
    x = get_terminal_size().columns
    print('\033[J\033[u' + (next(asd) * x) + '\r', end='')  # clear till the end of screen, and restores cursor
    time.sleep(1/60.)
```

**Comment by rsalmei** [comment] 2020-10-22 20:54
Oh, and a quick update!
The alive-progress is working again! The new "cells and graphemes" architecture is a success!
No more strings for frames, just tuples of cells! No more runtime generation of animations, they're compiled ahead of time! \o/
Now it's just the bar generation, stay tuned...

**Comment by MartinHammarstedt** [comment] 2020-10-23 11:27
Interesting find! I tried your code sample and it works as intended on Ubuntu. No flickering and no matter how fast I resize the window I can't get it to produce garbage.

I also tried it on Windows 10 with mixed results. Using the newer Windows Terminal (which sadly doesn't come preinstalled) it worked fine with no flickering, but some garbage when making the window smaller. Not a big problem. However, when using the good old Command Prompt (cmd.exe), which I think is still the default, it didn't work at all. It doesn't support ANSI escape codes, so the "\033[J\033[u" gets printed along with the rest and the screen fills up with lines immediately. That would be a problem if you're aiming to keep the current cross-platform compatibility.

**Comment by rsalmei** [comment] 2020-10-26 23:47
> Interesting find! I tried your code sample and it works as intended on Ubuntu. No flickering and no matter how fast I resize the window I can't get it to produce garbage.

Hey, that's very nice! Thank you for trying it, and I'm glad it worked so nicely!

But I think I'll let that for another time. I've tried several ways of expanding this to more simultaneous lines, to also support the exhibits like `showtime`, but couldn't find one that worked.
Also, I know there's some unofficial changes that support multiple alive-progress'es on screen at the same time (there's an issue for that), and if I include a Save/Restore cursor, I'll surely break it for them. It's never easy...

**Comment by rsalmei** [comment] 2020-10-27 01:47
Wow, the bar engine is finally working!! 😅 🎉
Now with complete support for Emojis and exotic Unicode chars!
Also, support for borders of any length, and underflow error that can leap to border if it can't fit!

Normal fill
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/6652853/97246222-93ce9c80-17db-11eb-97e2-aa62462565a0.png">

Transparent fill
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/6652853/97246864-2b80ba80-17dd-11eb-8d84-8e67efa62780.png">

Happy Halloween!

**Comment by rsalmei** [comment] 2020-10-28 17:59
The spinner compiler is finally committed, if someone would like to see it: https://github.com/rsalmei/alive-progress/pull/51/files#diff-9a805270b34f6ee2dca22ce24aeff16ed6aacd22b561c9b41e882cf36e3073a6
Also the new spinners and bars implementation: https://github.com/rsalmei/alive-progress/pull/51/files#diff-b583fc3cbfe4afdf1eb2bd1b652567d81fb35cd01c40f230f06f1b593c0f9eff and https://github.com/rsalmei/alive-progress/pull/51/files#diff-976ae5d099e58857be2c026362575a4bcca35f78ff1fc096ba3cdf82ba2616aa
\o/

**Comment by TheTechRobo** [comment] 2021-01-04 19:41
If you're still having issues with the escape codes on Windows CMD, try adding the colorama package to the requirements. All it does it make the escape codes work on windows.

https://pypi.org/project/colorama/#usage

**Comment by rsalmei** [comment] 2021-01-05 21:23
Cool tip @TheTechRobo, thanks.

**Comment by rsalmei** [comment] 2021-01-09 00:26
Closing the ready issues to reduce the number of opened ones.

**Closed by rsalmei** 2021-01-09 00:26 UTC
Labels: feature request, ready for release
