### ISSUE TITLE
Odd characters in Windows cmd output

### ISSUE THREAD

**Issue by DaveYarrow** [rsalmei/alive-progress#174] opened 2022-06-28 10:18 UTC
Hi,
I'm using alive-progress on Windows 10 but am seeing odd ? characters in the progress bar output
![chars](https://user-images.githubusercontent.com/108335907/176155452-9c95ff85-d9fc-4639-99eb-cbc95883bfc7.png)
.
```
from alive_progress import alive_bar
import time


with alive_bar(1000, force_tty=True) as bar:
	for i in range(1000):
		time.sleep(.005)
		bar()
```

The output is in a standard cmd terminal window.

How do I get rid of the ? characters?

EDIT: It seems to be a problem with some spinner/bar types and Truetype fonts in Windows.  Raster fonts work fine, but a number of the bar types (waves included) don't work with the truetype fonts.

**Comment by TheTechRobo** [comment] 2022-06-28 12:04
Related to #97, #88, #161, #96.

**Comment by rsalmei** [comment] 2022-06-28 18:37
Hi, that is caused by the default windows terminal. As you've told, it doesn't like TrueType fonts...
I'm not familiar with windows development, but I think there is a newer terminal in 10, have you tried it?
Also, read the related issues above for other tips, like installing a nerd-font.

Closing this one, but feel free to reply if more help is needed.

**Closed by rsalmei** 2022-06-28 18:37 UTC
