### ISSUE TITLE
Buffers issue using manual mode

### ISSUE THREAD

**Issue by CLDiego** [rsalmei/alive-progress#164] opened 2022-05-25 13:14 UTC
Hi,

First of all, thanks for this amazing library. I'm trying to use `alive-progress` to show the progress of receiving a file.

In essence I have a class which attributes change using callbacks related to the receiving process. 
I'm using the manual mode of `alive_bar`. This is the piece of code I'm having trouble with:

```python3
try:
     with alive_bar(manual=True, total=80000) as bar:
          while True:
               if self.status == 'LIVE' and self.prev_stat == 'SENDING':
                    bar(1)
                    break
               bar(self.file_size/80000)
                        
except Exception as err:
     print(f'ERROR OCURRED {err}')
     traceback.print_exc()
     raise err   
```

I'm getting an error related to the `flush_buffers()` -> `RuntimeError: dictionary changed size during iteration` 

The bar works well for at least 6 runs (i.e. reaching the  `break` six times). And then I'm prompted the error above.

Any suggestions on how to fix this issue? 

Thanks!

**Comment by rsalmei** [comment] 2022-05-26 07:51
Thanks man!

Please post the stack trace, it's way harder to try to understand it this way.
I can't make sense of your "6 runs", since the code you showed runs just once.

**Comment by rsalmei** [comment] 2022-06-15 03:11
Hey @CLDiego?

**Comment by rsalmei** [comment] 2022-06-17 02:36
Well, closing this one. Whenever you can, just reply here and we can continue...

**Closed by rsalmei** 2022-06-17 02:36 UTC

**Comment by dnsglk** [comment] 2022-10-15 11:48
Hey @rsalmei , I think I've caught the same issue.  My code is running threads which log via logging module. 
Here's the stack trace: 

```Traceback (most recent call last):
  File "run.py", line 61, in run
    bar(total_done_now - prev_total_done)
  File "/home/user/.local/lib/python3.10/site-packages/alive_progress/core/progress.py", line 357, in __call__
    self._handle(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/alivkalie_progress/core/progress.py", line 157, in bar_handle
    hook_manager.flush_buffers()
  File "/home/user/.local/lib/python3.10/site-packages/alive_progress/core/hook_manager.py", line 29, in flush_buffers
    for stream, buffer in buffers.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by rsalmei** [comment] 2022-10-16 01:01
That's very interesting, thanks @dnsglk!

But it is weird, I can't imagine any situation where that dict would change size _after_ the bat started...
Would you be able to create a minimum example that triggers this error?

**Comment by dnsglk** [comment] 2022-10-16 06:25
@rsalmei Sure, I'll try to devise an example, though the issue is not persistent and hard to catch.

**Comment by dnsglk** [comment] 2022-11-01 17:44
@rsalmei Sorry, it seems the issue doesn't want to reproduce anymore. I've run may times the same code, but have never run into it again. If it happens again, I'll make sure to post it here again.

**Comment by rsalmei** [comment] 2022-11-01 17:48
That's good news! 👍

**Comment by dnsglk** [comment] 2022-11-25 12:35
@rsalmei I've run again into the issue. And I guess it might be related to the number of threads my script is running. Each thread writes to the log, and it can be around 300 line per second. I can't boil it down further. But I see that the number of concurrent writes correlate with the issue appearance.
I use only one logger in all threads, get it from calling _logging.getLogger()_ and prepare it before using bar: attach two handlers - one for color formatting which gets into the console, and one for writing to a file.
