### ISSUE TITLE
Certain characters not displayed correctly

### ISSUE THREAD

**Issue by Ciross** [rsalmei/alive-progress#160] opened 2022-04-30 12:35 UTC
So I tried alive-progress in python using VScode.
At the start everything was good as I started the script in VScode terminal.
But when I double click it, or convert it in exe and start it, certain char aren't displayed correctly.
![example](https://user-images.githubusercontent.com/83854034/166105820-66df1ecc-33f8-48ff-9e44-eb56cd77d4dd.png)

**Comment by TheTechRobo** [comment] 2022-04-30 13:54
Possible duplicate of #88

**Comment by rsalmei** [comment] 2022-04-30 21:52
Is it in Windows? Which Python?
What do you mean by "when double click it", or by "convert it in exe"??

**Comment by TheTechRobo** [comment] 2022-05-01 14:13
I think this might be a cmd problem.

By "convert it in exe" they might mean Pyinstaller or something similar. Double-clicking on one of those brings up CMD, I think.

**Comment by rsalmei** [comment] 2022-05-20 00:15
Yeah, I think so too! Please look at the other tickets related to this.

**Closed by rsalmei** 2022-05-20 00:15 UTC
