### ISSUE TITLE
Progress bar display issue with dual_line=True when force_tty=True is needed

### ISSUE THREAD

**Issue by alllexx88** [rsalmei/alive-progress#185] opened 2022-08-28 10:47 UTC
First of all, thanks a lot for `alive-progress`! I find it cool and very useful.
I've noticed an issue in environments that require `force_tty=True` when `dual_line=True` is enabled, like in Jupyter notebooks or in PyCharm without enabling terminal emulation: the progress bar gets printed as new lines instead of being updated; see screenshot below.

![Screenshot_20220824_122824](https://user-images.githubusercontent.com/6587516/187070029-e1368c04-f6f1-48a9-959c-483ac1c5e0b4.png)

While it is easy to work around in PyCharm, that is not the case with Jupyter notebooks.

Thanks :smiley:

**Comment by TheTechRobo** [comment] 2022-08-28 15:05
The PyCharm issue is a duplicate of #173, for what it's worth.

**Comment by alllexx88** [comment] 2022-08-28 15:21
Yes, there's a workaround you can use in PyCharm (which I also mentioned above), but not in all other cases that require `force_tty=True`, say, in Jupyter notebooks:
![Screenshot_20220828_171708](https://user-images.githubusercontent.com/6587516/187081443-c3e979c9-85e9-46d7-9408-8c8602fd3790.png)
And it works okay without `dual_line=True`
![Screenshot_20220828_171934](https://user-images.githubusercontent.com/6587516/187081508-7576bcd9-e989-4dd1-86c9-15aca74d1c34.png)

**Comment by rsalmei** [comment] 2022-08-29 03:01
Hi @alllexx88, thank you.

I've already told here, a lot of times actually, that Jupyter **does not support ANSI Escape Codes**.
This means it simply **ignores** the command to make the cursor go up and refresh the previous line, thus it is **impossible** to make dual line work on it.

Actually, it even ignores the most basic commands, like the one to clear the current line! I had to print several spaces at the end of the line to work around that and clear the garbage from the last line...
The same can be said about Pycharm _without terminal emulation_. These needed commands are ignored if this option is not enabled, so it doesn't even make sense to try to run it there like this. I don't even understand why would Jetbrains require an option to make the terminal actually work, it seems silly to me.

That's it, I expect it should be pretty clear by now that these fancier modes **require** a terminal. It simply can't be done if the environment summarily ignores the needed cursor commands.

**Closed by rsalmei** 2022-08-29 03:01 UTC

**Comment by alllexx88** [comment] 2022-08-29 08:24
@rsalmei , thanks a lot for your explanation and your great efforts to keep `alive-progress` going. Have a great week!

**Comment by rsalmei** [comment] 2022-08-29 21:27
Thank you @alllexx88, have a good one too! 👋
